controller_list:
  - name: fake_ur10_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    joints:
      - palm_to_finger1
      - palm_to_finger2
initial:  # Define initial robot poses.
  - group: ur10_arm
    pose: home